### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by zslabs** [SimonSiefke/vscode-svg-preview#10]
Not an issue, but wanted to pass along a huge thanks for creating this! I've been trying out a few other SVG tools for VS Code and all have been varying degrees of buggy, except for yours. Really like the style option as well -- was able to replicate Atom's preview by using the following:

```json
  "svgPreview.style": {
    "html": {
      "padding": "32px",
      "background-color": "#e3e3e3",
      "background-size": "10px 10px",
      "background-position": "0 0, 5px 5px",
      "background-image": "linear-gradient(45deg, #ffffff 25%, transparent 25%, transparent 75%, #ffffff 75%, #ffffff), linear-gradient(45deg, #ffffff 25%, transparent 25%, transparent 75%, #ffffff 75%, #ffffff)"
    }
```

Have a great day!

**Comment by SimonSiefke** [comment]
:)
