### ISSUE TITLE
Zoom Preference

### ISSUE THREAD

**Issue by zslabs** [SimonSiefke/vscode-svg-preview#11]
@SimonSiefke Would it be possible to set the starting zoom-level as a preference? It looks like by default it'll fill up the viewport, but seeing the icon in its actual-size would be pretty nice.

**Comment by SimonSiefke** [comment]
Thanks for the feedback. I have added a `scaleToFit` option to the extension. 
Setting `"svgPreview.scaleToFit": false` disables that images fill up the whole viewport.

**Comment by zslabs** [comment]
Thanks!
