### ISSUE TITLE
Support css custom properties

### ISSUE THREAD

**Issue by IanVS** [SimonSiefke/vscode-svg-preview#36]
I would like to use css custom properties in my svg files, which works fine, except that the preview doesn't know what to do with them, since they're set in my app and not in the svg file itself.  Is there a way to set the values in the `"svgPreview.style"` setting?  I've tried and haven't quite found a way to make it work yet. 

Thanks!

**Comment by SimonSiefke** [comment]
Thanks for the suggestion. You can now define CSS variables in the settings, e.g.
```json
{
  "svgPreview.style": {
    "html": {
      "--red": "orangered"
    }
  }
}
```
 or 

```json
{
  "svgPreview.style": {
    "img": {
      "--red": "orangered"
    }
  }
}
```
