### ISSUE TITLE
Initial view is confusing if the height is greater than the width

### ISSUE THREAD

**Issue by shruda** [SimonSiefke/vscode-svg-preview#39]
Hi,
the initial view of the preview tab is confusing if the height is greater than the width:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 100">
    <rect fill="#FF0000" width="20" height="100" /> 
    <rect fill="#000000" x="5" y="20" width="10" height="80" /> 
</svg>`

Current result:
![image](https://user-images.githubusercontent.com/4671906/72737458-e8cfe900-3b9f-11ea-8c39-d1900ae42c2e.png)

I would the following view:
![image](https://user-images.githubusercontent.com/4671906/72737438-de155400-3b9f-11ea-93e9-e1880f2ef3c9.png)

**SvgPreview Version: 2.8.1**

Best Regards,
Steve

**Comment by SimonSiefke** [comment]
Fixed in version 2.8.2 :)
