### ISSUE TITLE
Docs: add a Windows "translation" for the Mac "Command-I" feature

### ISSUE THREAD

**Issue by americrypt** [SimonSiefke/vscode-svg-preview#87]
@SimonSiefke In the demo gif you displayed some editing wizardry which this PC bound coder cannot seem to duplicate. You showed using Mac "Command-I" ('eye') or "Command-l" (lower case 'el') to increment & decrement a value. The video isn't clear if its 'eye' or 'el'.

Usually Mac "Command" maps to the "Windows button", but I can't get it to work. I can tell you what Windows-L does though: locks you out of your PC  :)  Yeah, fun times.

What is the Windows keystroke to make that happen and can you put it in your readme.md someplace? Thanks. Just got your extension tonight and really liking it so far.

**Comment by SimonSiefke** [comment]
I'm using the [Incrementor Extension](https://marketplace.visualstudio.com/items?itemName=nmsmith89.incrementor), which lets you increment with <kbd>Ctrl+i</kbd> and decrement with <kbd>Ctrl+Shift+i</kbd> :)

**Comment by americrypt** [comment]
Thank you @SimonSiefke - when editing SVG's the combination of [Incrementor Extension](https://marketplace.visualstudio.com/items?itemName=nmsmith89.incrementor) and your SVG preview extension is really nice! Kudos and thanks for the assist - highly rated.
